os: linux

language: node_js

node_js:
  - 12.14.0

# Safelist
branches:
  only:
    - develop

cache:
  npm: true
  pip: true

script:
  - npm run test:stylelint
  - npm run test:eslint
  - npm run build

jobs:
  include:
    - before_script:
        - npm i
      script:
        - npm run test:stylelint
        - npm run test:eslint
        - npm run build
        - cd web
      deploy:
        provider: pages
        cleanup: false
        token: $GITHUB_TOKEN
        target_branch: master
        keep_history: false
        edge: true
        commit_message: Deploy Travis CI to %{target_branch} branch
        on:
          branch: develop
