name: Build

on:
  merge_group:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    uses: yoriiis/actions/.github/workflows/test-and-build.yml@main
    with:
      node-version: 12
      command-build: npm run build