name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  github:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: yoriiis/actions/.github/workflows/github-pages-deploy.yml@main
    with:
      node-version: 12
      build-dir: web